[model]
name = "PrimeIntellect/llama-14m-fresh"

[tokenizer]
name = "meta-llama/Llama-2-7b-hf"

[data]
path = "Salesforce/wikitext"
name = "wikitext-2-raw-v1"
seq_length = 1024

[train]
max_steps = -1
max_epochs = 1
batch_size = 512

[train.optimizer]

[train.scheduler]
enable = false

[eval]
enable = true
every_n_steps = -1

[logging.console]
enable = true

[logging.wandb]
enable = true
group = "verify/perf"

[logging.file]
enable = true

[logging.ckpt]
enable = false
