[data]
seq_length = 1024

[train]
max_steps = -1
max_epochs = 1
batch_size = 512
micro_batch_size = 1

[train.optimizer]

[train.scheduler]
enable = false

[eval]
enable = true
every_n_steps = -1

[logging.console]
enable = true

[logging.wandb]
enable = true

[logging.file]
enable = true

[logging.ckpt]
enable = false
