[data]
path = "Salesforce/wikitext"
name = "wikitext-2-raw-v1"
seq_length = 128

[train]
max_steps = 10
max_epochs = -1
micro_batch_size = 1
batch_size = 32

[train.optimizer]

[train.scheduler]
enable = false

[eval]
enable = false

[logging.console]
enable = true

[logging.ckpt]
enable = false

[logging.wandb]
enable = false

[logging.file]
enable = true