[data]
seq_length = 128
subset_size = 0.05

[train]
max_steps = 10
batch_size = 32
micro_batch_size = 16
max_norm = 1000.0 # Disable gradient clipping (for debugging PP)

[eval]
every_n_steps = 5
max_steps = 5