[data]
seq_length = 1024

[train]
max_steps = -1 # ~1.900 steps for 1B tokens
max_epochs = 1
batch_size = 512
micro_batch_size = 8

[train.scheduler]
enable = true

[sample]
enable = true
every_n_steps = 50

[eval]
enable = true
max_steps = 10
every_n_steps = 50

[logging.wandb]
enable = true

[logging.file]
enable = true

[logging.ckpt]
enable = true
every_n_steps = 50
